name: State Software Collaborative
URL:  https://www.softwarecollaborative.org/
remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
minima:
  social_links:
    twitter: statesoftware
    github: State-Software-Collaborative

links:
  home: /
  collaboratives: /collaboratives/
