name: State Software Collaborative
URL:  https://www.softwarecollaborative.org/
theme: minima
minima:
  social_links:
    twitter: statesoftware
    github: State-Software-Collaborative

links:
  home: /
  collaboratives: /collaboratives/
